apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
permissions:
  id-token: read|write
b.  u:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Hello
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          echo "hello world"