apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  u:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Hello
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          echo "hello world"
