apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      a:
        type: string
      n:
        type: number
      asdf:
        type: boolean
        default: false
        description: b
      c:
        type: choice
        options:
          - as
          - asdff
          - sadfasdf
        default: ""
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
